### ISSUE TITLE
This looks cool! ✨

### ISSUE THREAD

**Issue by GrantBirki** [rick/branch-deploy#8]
👋 Hey @rick!

I stumbled across this today and read through your roadmap. I think this project looks really cool and would pair nicely with [github/branch-deploy](https://github.com/github/branch-deploy) (of the same name 😂).

I do the following all the time in my personal projects, and a few open source projects that I maintain:

1. Trigger a branch deployment on a PR via a comment `.deploy` (through github/branch-deploy)
2. Do a remote deployment by SSHing into a VM and then calling `script/deploy` on the remote server running an app
3. 🚀 

Looking at this project, it looks like it would be a lot better and more robust to use `bd` rather than a what I'm currently doing which is poorly crafted shell scripts that _work_(ish).

You might also find this project interesting -> [runwaylab/runway](https://github.com/runwaylab/runway). Its an experimental side project that I tossed together to allow branch-deployments to be "completed" by a deployment controller on my homelab so I can still get all the branch-deploy goodies without having to expose a webhook server on my home network.

**Comment by rick** [comment]
Thanks, @GrantBirki! I made a big push on this back in the day and then stalled out, started doing contract work, and haven't picked it back up again. Maybe one day!
